import { Capacitor } from '@capacitor/core';
import HealthConnect from '../lib/healthConnect';

export interface HealthDataReport {
  steps: number;
  calories: number;
  source: 'health_connect' | 'mock_or_local';
  timestamp: string;
}

export interface SyncStatus {
  success: boolean;
  message: string;
  code: 'SUCCESS' | 'NOT_ANDROID' | 'UNSUPPORTED' | 'UPDATE_REQUIRED' | 'PERMISSION_DENIED' | 'ERROR';
}

/**
 * Service to manage secure, defensive access to Health Connect on Android and handle fallbacks gracefully.
 */
export const HealthConnectService = {
  /**
   * Safe check for whether Health Connect is supported and available on this device.
   * Handles non-Android platform environments gracefully.
   */
  async getAvailability(): Promise<SyncStatus> {
    if (Capacitor.getPlatform() !== 'android') {
      return {
        success: false,
        message: 'Health Connect integration is only supported on native Android setups.',
        code: 'NOT_ANDROID',
      };
    }

    try {
      const status = await HealthConnect.checkStatus();
      if (status.isAvailable) {
        return {
          success: true,
          message: 'Health Connect is active and ready.',
          code: 'SUCCESS',
        };
      } else if (status.updateRequired) {
        return {
          success: false,
          message: 'Health Connect is supported, but an application update is required from the Google Play Store.',
          code: 'UPDATE_REQUIRED',
        };
      } else {
        return {
          success: false,
          message: 'Health Connect is not supported or inactive on this device.',
          code: 'UNSUPPORTED',
        };
      }
    } catch (e: any) {
      return {
        success: false,
        message: `Compatibility check failed: ${e?.message || 'Unknown error'}`,
        code: 'ERROR',
      };
    }
  },

  /**
   * Asserts read permissions, and maps access parameters.
   */
  async ensurePermissions(): Promise<SyncStatus> {
    const availability = await this.getAvailability();
    if (!availability.success) {
      return availability;
    }

    try {
      const auth = await HealthConnect.checkAndRequestPermissions();
      if (auth.granted) {
        return {
          success: true,
          message: 'Access permissions verified.',
          code: 'SUCCESS',
        };
      } else {
        return {
          success: false,
          message: 'Permissions are required to sync steps and calories from walking/jogging activities.',
          code: 'PERMISSION_DENIED',
        };
      }
    } catch (e: any) {
      return {
        success: false,
        message: `Permission request failed: ${e?.message || 'Unknown error'}`,
        code: 'ERROR',
      };
    }
  },

  /**
   * Queries total steps and active calories burner specifically generated by walking or jogging activities today.
   */
  async syncTodayMetrics(dateIsoString?: string): Promise<{ status: SyncStatus; data?: HealthDataReport }> {
    const check = await this.ensurePermissions();
    if (!check.success) {
      return { status: check };
    }

    try {
      // Query native Health Connect through our Capacitor custom plugin bridge
      const metrics = await HealthConnect.queryWalkingJoggingMetrics({ date: dateIsoString });
      
      return {
        status: {
          success: true,
          message: 'Synchronized health metrics successfully.',
          code: 'SUCCESS',
        },
        data: {
          steps: metrics.steps,
          calories: Math.round(metrics.calories * 10) / 10, // Round to 1 decimal place
          source: 'health_connect',
          timestamp: new Date().toISOString(),
        }
      };
    } catch (e: any) {
      return {
        status: {
          success: false,
          message: `Data synchronization failed: ${e?.message || 'Unknown error'}`,
          code: 'ERROR',
        }
      };
    }
  }
};
