package com.serene.healthtracker

import android.content.Context
import androidx.health.connect.client.HealthConnectClient
import androidx.health.connect.client.permission.HealthPermission
import androidx.health.connect.client.records.ExerciseSessionRecord
import androidx.health.connect.client.records.StepsRecord
import androidx.health.connect.client.records.TotalCaloriesBurnedRecord
import androidx.health.connect.client.request.ReadRecordsRequest
import androidx.health.connect.client.time.TimeRangeFilter
import java.time.Instant

enum class SdkStatus {
    AVAILABLE,
    PROVIDER_UPDATE_REQUIRED,
    UNAVAILABLE
}

object HealthConnectManager {

    val PERMISSIONS = setOf(
        HealthPermission.getReadPermission(StepsRecord::class),
        HealthPermission.getReadPermission(TotalCaloriesBurnedRecord::class)
    )

    /**
     * Checks the integration capability status of Health Connect on the client.
     */
    fun checkHealthConnectStatus(context: Context): SdkStatus {
        return try {
            val status = HealthConnectClient.getSdkStatus(context)
            when (status) {
                HealthConnectClient.SDK_AVAILABLE -> SdkStatus.AVAILABLE
                HealthConnectClient.SDK_UNAVAILABLE_PROVIDER_UPDATE_REQUIRED -> SdkStatus.PROVIDER_UPDATE_REQUIRED
                else -> SdkStatus.UNAVAILABLE
            }
        } catch (e: Exception) {
            SdkStatus.UNAVAILABLE
        }
    }

    /**
     * Helper checking if the caller possesses all defined Read-Permissions for health items.
     */
    suspend fun hasAllPermissions(context: Context): Boolean {
        if (checkHealthConnectStatus(context) != SdkStatus.AVAILABLE) {
            return false
        }
        return try {
            val client = HealthConnectClient.getOrCreate(context)
            val granted = client.permissionController.getGrantedPermissions()
            granted.containsAll(PERMISSIONS)
        } catch (e: Exception) {
            false
        }
    }

    /**
     * Reads Total Steps (StepsRecord) and Total Calories Burned (TotalCaloriesBurnedRecord)
     * specifically generated by walking or running/jogging activities over a specified time range.
     * 
     * It does this by querying individual exercise sessions, selecting those with walking
     * or running exercise profiles, and querying detailed metrics over matching session time ranges.
     */
    suspend fun readWalkingJoggingData(
        context: Context,
        startTime: Instant,
        endTime: Instant
    ): Pair<Long, Double> {
        if (checkHealthConnectStatus(context) != SdkStatus.AVAILABLE) {
            return Pair(0L, 0.0)
        }
        
        try {
            val client = HealthConnectClient.getOrCreate(context)

            // 1. Fetch walking and running exercise sessions in the given time frame
            val sessionRequest = ReadRecordsRequest(
                recordType = ExerciseSessionRecord::class,
                timeRangeFilter = TimeRangeFilter.between(startTime, endTime)
            )
            val sessionsResult = client.readRecords(sessionRequest)

            // Filter exercise sessions exclusively for WALKING and RUNNING/JOGGING classes
            val activeSessions = sessionsResult.records.filter { session ->
                session.exerciseType == ExerciseSessionRecord.EXERCISE_TYPE_WALKING ||
                session.exerciseType == ExerciseSessionRecord.EXERCISE_TYPE_RUNNING
            }

            var totalSteps = 0L
            var totalCalories = 0.0

            // 2. Overlap metrics queries for the duration of each walking/jogging session
            for (session in activeSessions) {
                val sessionStart = session.startTime
                val sessionEnd = session.endTime

                // Read StepsRecord for the exact duration of this walking/jogging exercise
                val stepsRequest = ReadRecordsRequest(
                    recordType = StepsRecord::class,
                    timeRangeFilter = TimeRangeFilter.between(sessionStart, sessionEnd)
                )
                val stepsResult = client.readRecords(stepsRequest)
                for (record in stepsResult.records) {
                    totalSteps += record.count
                }

                // Read TotalCaloriesBurnedRecord for the exact duration of this walking/jogging exercise
                val caloriesRequest = ReadRecordsRequest(
                    recordType = TotalCaloriesBurnedRecord::class,
                    timeRangeFilter = TimeRangeFilter.between(sessionStart, sessionEnd)
                )
                val caloriesResult = client.readRecords(caloriesRequest)
                for (record in caloriesResult.records) {
                    totalCalories += record.energy.inKilocalories
                }
            }

            return Pair(totalSteps, totalCalories)
        } catch (e: Exception) {
            // Quietly fallback or handle read constraints
            return Pair(0L, 0.0)
        }
    }
}
